version: '3.3'

services:
  authentication:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - /opt/auth:/auth

    entrypoint: 
      - htpasswd -Bbn $HTAUSER $HTPASS > auth/htpasswd

  registry:
    depends_on:
      - authentication
    restart: always
    image: registry:2
    ports:
      - 443:5000
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - /mnt/registry:/var/lib/registry
      - /opt/certs:/certs
      - /opt/auth:/auth
